osx_image: xcode10.2

language: node_js
node_js: '10'

os:
  - osx
  - windows

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

install:
  - npm i

script:
  - echo "Build win"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run dist:win; fi

  - echo "Build mac"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist:mac; fi
